# config.yaml
parameters:
  ScanNumThres: 150 # 50
  GRID_RESOLUTION: 0.1 # 3.0
  X_MIN: -5 # 20
  X_MAX: 5
  Y_MIN: -5
  Y_MAX: 5
  Z_MIN: -5
  Z_MAX: 5
  PCD_file: "/home/lj/yf_ws/src/FAST_LIO/Debugnoise" # PCD 文件路径 这个没有用

  
